set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullnone [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports FPGA_RESET]
set_property PACKAGE_PIN F13 [get_ports FPGA_RESET]
set_property IOSTANDARD LVCMOS18 [get_ports USER_SMA_CLOCK]
set_property PACKAGE_PIN U20 [get_ports USER_SMA_CLOCK]
set_property IOSTANDARD LVDS_25 [get_ports FPGA_MASTER_CLOCK_P]
set_property IOSTANDARD LVDS_25 [get_ports FPGA_MASTER_CLOCK_N]
set_property PACKAGE_PIN J19 [get_ports FPGA_MASTER_CLOCK_P]
set_property PACKAGE_PIN H19 [get_ports FPGA_MASTER_CLOCK_N]

set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[0]}]
set_property PACKAGE_PIN AB17 [get_ports {AD9265_DATA[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[1]}]
set_property PACKAGE_PIN AA16 [get_ports {AD9265_DATA[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[2]}]
set_property PACKAGE_PIN AB16 [get_ports {AD9265_DATA[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[3]}]
set_property PACKAGE_PIN AA15 [get_ports {AD9265_DATA[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[4]}]
set_property PACKAGE_PIN Y14 [get_ports {AD9265_DATA[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[5]}]
set_property PACKAGE_PIN AB13 [get_ports {AD9265_DATA[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[6]}]
set_property PACKAGE_PIN AB15 [get_ports {AD9265_DATA[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[7]}]
set_property PACKAGE_PIN AA14 [get_ports {AD9265_DATA[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[8]}]
set_property PACKAGE_PIN AB12 [get_ports {AD9265_DATA[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[9]}]
set_property PACKAGE_PIN AA13 [get_ports {AD9265_DATA[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[10]}]
set_property PACKAGE_PIN Y13 [get_ports {AD9265_DATA[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[11]}]
set_property PACKAGE_PIN Y12 [get_ports {AD9265_DATA[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[12]}]
set_property PACKAGE_PIN AA11 [get_ports {AD9265_DATA[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[13]}]
set_property PACKAGE_PIN AB11 [get_ports {AD9265_DATA[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[14]}]
set_property PACKAGE_PIN W10 [get_ports {AD9265_DATA[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {AD9265_DATA[15]}]
set_property PACKAGE_PIN AB10 [get_ports {AD9265_DATA[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports AD9265_DCO]
set_property PACKAGE_PIN W11 [get_ports AD9265_DCO]
set_property IOSTANDARD LVCMOS18 [get_ports AD9265_OR]
set_property PACKAGE_PIN AA10 [get_ports AD9265_OR]
set_property IOSTANDARD LVCMOS18 [get_ports AD9265_SYNC]
set_property PACKAGE_PIN W14 [get_ports AD9265_SYNC]
set_property IOSTANDARD LVCMOS18 [get_ports AD9265_PDWN]
set_property PACKAGE_PIN Y16 [get_ports AD9265_PDWN]
set_property IOSTANDARD LVCMOS18 [get_ports AD9265_SCLK]
set_property PACKAGE_PIN Y11 [get_ports AD9265_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports AD9265_CSB]
set_property PACKAGE_PIN V10 [get_ports AD9265_CSB]
set_property IOSTANDARD LVCMOS18 [get_ports AD9265_SDIO]
set_property PACKAGE_PIN AA9 [get_ports AD9265_SDIO]

set_property PACKAGE_PIN F6 [get_ports SFP_MGT_REFCLK_C_P]
set_property PACKAGE_PIN E6 [get_ports SFP_MGT_REFCLK_C_N]
set_property PACKAGE_PIN A8 [get_ports FPGA_SFP1_RX_N]
set_property PACKAGE_PIN B8 [get_ports FPGA_SFP1_RX_P]
set_property PACKAGE_PIN A4 [get_ports FPGA_SFP1_TX_N]
set_property PACKAGE_PIN B4 [get_ports FPGA_SFP1_TX_P]

# set_property IOSTANDARD LVCMOS18 [get_ports EEPROM_CS_B]
# set_property PACKAGE_PIN U17 [get_ports EEPROM_CS_B]
# set_property IOSTANDARD LVCMOS18 [get_ports EEPROM_SO]
# set_property PACKAGE_PIN U18 [get_ports EEPROM_SO]
# set_property IOSTANDARD LVCMOS18 [get_ports EEPROM_SI]
# set_property PACKAGE_PIN P14 [get_ports EEPROM_SI]
# set_property IOSTANDARD LVCMOS18 [get_ports EEPROM_WP_B]
# set_property PACKAGE_PIN R14 [get_ports EEPROM_WP_B]
# set_property IOSTANDARD LVCMOS18 [get_ports EEPROM_SCK]
# set_property PACKAGE_PIN R18 [get_ports EEPROM_SCK]

# set_property IOSTANDARD LVCMOS18 [get_ports TMP75_IIC_SDA]
# set_property PACKAGE_PIN T18 [get_ports TMP75_IIC_SDA]
# set_property IOSTANDARD LVCMOS18 [get_ports TMP75_IIC_SCL]
# set_property PACKAGE_PIN N17 [get_ports TMP75_IIC_SCL]
# set_property IOSTANDARD LVCMOS18 [get_ports TMP75_ALERT]
# set_property PACKAGE_PIN P17 [get_ports TMP75_ALERT]

set_property IOSTANDARD LVCMOS18 [get_ports DDR_POWER_GOOD]
set_property PACKAGE_PIN AB18 [get_ports DDR_POWER_GOOD]
set_property IOSTANDARD LVCMOS18 [get_ports VCC3V3_PG]
set_property PACKAGE_PIN R16 [get_ports VCC3V3_PG]
set_property IOSTANDARD LVCMOS18 [get_ports MGTAVTT_PG]
set_property PACKAGE_PIN N13 [get_ports MGTAVTT_PG]
set_property IOSTANDARD LVCMOS18 [get_ports VCC3V6_PG]
set_property PACKAGE_PIN N14 [get_ports VCC3V6_PG]
set_property IOSTANDARD LVCMOS18 [get_ports VCC_3V_A_PG]
set_property PACKAGE_PIN P16 [get_ports VCC_3V_A_PG]

set_property IOSTANDARD LVCMOS33 [get_ports VCC12V_FAN_EN]
set_property PACKAGE_PIN E13 [get_ports VCC12V_FAN_EN]

# SPI to Timming
set_property IOSTANDARD LVDS_25 [get_ports TIMING_SPI_SCLK_P]
set_property IOSTANDARD LVDS_25 [get_ports TIMING_SPI_SCLK_N]
set_property PACKAGE_PIN H17 [get_ports TIMING_SPI_SCLK_P]
set_property PACKAGE_PIN H18 [get_ports TIMING_SPI_SCLK_N]
set_property IOSTANDARD LVDS_25 [get_ports TIMING_SPI_MOSI_P]
set_property IOSTANDARD LVDS_25 [get_ports TIMING_SPI_MOSI_N]
set_property PACKAGE_PIN J14 [get_ports TIMING_SPI_MOSI_P]
set_property PACKAGE_PIN H14 [get_ports TIMING_SPI_MOSI_N]
set_property IOSTANDARD LVDS_25 [get_ports TIMING_SPI_MCLK_P]
set_property IOSTANDARD LVDS_25 [get_ports TIMING_SPI_MCLK_N]
set_property PACKAGE_PIN H13 [get_ports TIMING_SPI_MCLK_P]
set_property PACKAGE_PIN G13 [get_ports TIMING_SPI_MCLK_N]
set_property IOSTANDARD LVDS_25 [get_ports TIMING_SPI_MISO_P]
set_property IOSTANDARD LVDS_25 [get_ports TIMING_SPI_MISO_N]
set_property PACKAGE_PIN G17 [get_ports TIMING_SPI_MISO_P]
set_property PACKAGE_PIN G18 [get_ports TIMING_SPI_MISO_N]

set_property IOSTANDARD LVDS_25 [get_ports ENCODE_MCLK_P]
set_property IOSTANDARD LVDS_25 [get_ports ENCODE_MCLK_N]
set_property PACKAGE_PIN J15 [get_ports ENCODE_MCLK_P]
set_property PACKAGE_PIN H15 [get_ports ENCODE_MCLK_N]
set_property IOSTANDARD LVDS_25 [get_ports ENCODE_MOSI_P]
set_property IOSTANDARD LVDS_25 [get_ports ENCODE_MOSI_N]
set_property PACKAGE_PIN G15 [get_ports ENCODE_MOSI_P]
set_property PACKAGE_PIN G16 [get_ports ENCODE_MOSI_N]
# ACC
# set_property IOSTANDARD LVDS_25 [get_ports ACC_SCLK_P]
# set_property IOSTANDARD LVDS_25 [get_ports ACC_SCLK_N]
# set_property PACKAGE_PIN H20 [get_ports ACC_SCLK_P]
# set_property PACKAGE_PIN G20 [get_ports ACC_SCLK_N]
# set_property IOSTANDARD LVDS_25 [get_ports ACC_MISO_P]
# set_property IOSTANDARD LVDS_25 [get_ports ACC_MISO_N]
# set_property PACKAGE_PIN J22 [get_ports ACC_MISO_P]
# set_property PACKAGE_PIN H22 [get_ports ACC_MISO_N]

set_property IOSTANDARD LVCMOS33 [get_ports RF_ENABLE]
set_property PACKAGE_PIN D15 [get_ports RF_ENABLE]
set_property IOSTANDARD LVCMOS33 [get_ports RF_FAULT]
set_property PACKAGE_PIN B15 [get_ports RF_FAULT]

set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SFP1_TX_FAULT]
set_property PACKAGE_PIN F20 [get_ports FPGA_SFP1_TX_FAULT]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SFP1_TX_DISABLE]
set_property PACKAGE_PIN D20 [get_ports FPGA_SFP1_TX_DISABLE]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SFP1_MOD_DETECT]
set_property PACKAGE_PIN C20 [get_ports FPGA_SFP1_MOD_DETECT]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SFP1_RS0]
set_property PACKAGE_PIN C22 [get_ports FPGA_SFP1_RS0]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SFP1_RS1]
set_property PACKAGE_PIN B22 [get_ports FPGA_SFP1_RS1]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SFP1_LOS]
set_property PACKAGE_PIN B21 [get_ports FPGA_SFP1_LOS]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SFP1_IIC_SCL]
set_property PACKAGE_PIN A21 [get_ports FPGA_SFP1_IIC_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SFP1_IIC_SDA]
set_property PACKAGE_PIN E22 [get_ports FPGA_SFP1_IIC_SDA]

set_property IOSTANDARD LVCMOS33 [get_ports FPGA_VCC12V_BST_EN]
set_property PACKAGE_PIN E18 [get_ports FPGA_VCC12V_BST_EN]

set_property SLEW FAST [get_ports {DDR3_A_D[0]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[0]}]
set_property PACKAGE_PIN M5 [get_ports {DDR3_A_D[0]}]
set_property SLEW FAST [get_ports {DDR3_A_D[1]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[1]}]
set_property PACKAGE_PIN P2 [get_ports {DDR3_A_D[1]}]
set_property SLEW FAST [get_ports {DDR3_A_D[2]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[2]}]
set_property PACKAGE_PIN M6 [get_ports {DDR3_A_D[2]}]
set_property SLEW FAST [get_ports {DDR3_A_D[3]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[3]}]
set_property PACKAGE_PIN R1 [get_ports {DDR3_A_D[3]}]
set_property SLEW FAST [get_ports {DDR3_A_D[4]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[4]}]
set_property PACKAGE_PIN N2 [get_ports {DDR3_A_D[4]}]
set_property SLEW FAST [get_ports {DDR3_A_D[5]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[5]}]
set_property PACKAGE_PIN P6 [get_ports {DDR3_A_D[5]}]
set_property SLEW FAST [get_ports {DDR3_A_D[6]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[6]}]
set_property PACKAGE_PIN P1 [get_ports {DDR3_A_D[6]}]
set_property SLEW FAST [get_ports {DDR3_A_D[7]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[7]}]
set_property PACKAGE_PIN N5 [get_ports {DDR3_A_D[7]}]
set_property SLEW FAST [get_ports {DDR3_A_D[8]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[8]}]
set_property PACKAGE_PIN K6 [get_ports {DDR3_A_D[8]}]
set_property SLEW FAST [get_ports {DDR3_A_D[9]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[9]}]
set_property PACKAGE_PIN L3 [get_ports {DDR3_A_D[9]}]
set_property SLEW FAST [get_ports {DDR3_A_D[10]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[10]}]
set_property PACKAGE_PIN M2 [get_ports {DDR3_A_D[10]}]
set_property SLEW FAST [get_ports {DDR3_A_D[11]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[11]}]
set_property PACKAGE_PIN J6 [get_ports {DDR3_A_D[11]}]
set_property SLEW FAST [get_ports {DDR3_A_D[12]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[12]}]
set_property PACKAGE_PIN M3 [get_ports {DDR3_A_D[12]}]
set_property SLEW FAST [get_ports {DDR3_A_D[13]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[13]}]
set_property PACKAGE_PIN L4 [get_ports {DDR3_A_D[13]}]
set_property SLEW FAST [get_ports {DDR3_A_D[14]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[14]}]
set_property PACKAGE_PIN L5 [get_ports {DDR3_A_D[14]}]
set_property SLEW FAST [get_ports {DDR3_A_D[15]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[15]}]
set_property PACKAGE_PIN K3 [get_ports {DDR3_A_D[15]}]
set_property SLEW FAST [get_ports {DDR3_A_D[16]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[16]}]
set_property PACKAGE_PIN H2 [get_ports {DDR3_A_D[16]}]
set_property SLEW FAST [get_ports {DDR3_A_D[17]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[17]}]
set_property PACKAGE_PIN H3 [get_ports {DDR3_A_D[17]}]
set_property SLEW FAST [get_ports {DDR3_A_D[18]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[18]}]
set_property PACKAGE_PIN G2 [get_ports {DDR3_A_D[18]}]
set_property SLEW FAST [get_ports {DDR3_A_D[19]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[19]}]
set_property PACKAGE_PIN J1 [get_ports {DDR3_A_D[19]}]
set_property SLEW FAST [get_ports {DDR3_A_D[20]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[20]}]
set_property PACKAGE_PIN G4 [get_ports {DDR3_A_D[20]}]
set_property SLEW FAST [get_ports {DDR3_A_D[21]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[21]}]
set_property PACKAGE_PIN J5 [get_ports {DDR3_A_D[21]}]
set_property SLEW FAST [get_ports {DDR3_A_D[22]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[22]}]
set_property PACKAGE_PIN G3 [get_ports {DDR3_A_D[22]}]
set_property SLEW FAST [get_ports {DDR3_A_D[23]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[23]}]
set_property PACKAGE_PIN H4 [get_ports {DDR3_A_D[23]}]
set_property SLEW FAST [get_ports {DDR3_A_D[24]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[24]}]
set_property PACKAGE_PIN F1 [get_ports {DDR3_A_D[24]}]
set_property SLEW FAST [get_ports {DDR3_A_D[25]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[25]}]
set_property PACKAGE_PIN D2 [get_ports {DDR3_A_D[25]}]
set_property SLEW FAST [get_ports {DDR3_A_D[26]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[26]}]
set_property PACKAGE_PIN F3 [get_ports {DDR3_A_D[26]}]
set_property SLEW FAST [get_ports {DDR3_A_D[27]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[27]}]
set_property PACKAGE_PIN C2 [get_ports {DDR3_A_D[27]}]
set_property SLEW FAST [get_ports {DDR3_A_D[28]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[28]}]
set_property PACKAGE_PIN E2 [get_ports {DDR3_A_D[28]}]
set_property SLEW FAST [get_ports {DDR3_A_D[29]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[29]}]
set_property PACKAGE_PIN B1 [get_ports {DDR3_A_D[29]}]
set_property SLEW FAST [get_ports {DDR3_A_D[30]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[30]}]
set_property PACKAGE_PIN G1 [get_ports {DDR3_A_D[30]}]
set_property SLEW FAST [get_ports {DDR3_A_D[31]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_D[31]}]
set_property PACKAGE_PIN A1 [get_ports {DDR3_A_D[31]}]
set_property SLEW FAST [get_ports {DDR3_A_DQS_P[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {DDR3_A_DQS_P[0]}]
set_property SLEW FAST [get_ports {DDR3_A_DQS_N[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {DDR3_A_DQS_N[0]}]
set_property PACKAGE_PIN P5 [get_ports {DDR3_A_DQS_P[0]}]
set_property PACKAGE_PIN P4 [get_ports {DDR3_A_DQS_N[0]}]
set_property SLEW FAST [get_ports {DDR3_A_DQS_P[1]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {DDR3_A_DQS_P[1]}]
set_property SLEW FAST [get_ports {DDR3_A_DQS_N[1]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {DDR3_A_DQS_N[1]}]
set_property PACKAGE_PIN M1 [get_ports {DDR3_A_DQS_P[1]}]
set_property PACKAGE_PIN L1 [get_ports {DDR3_A_DQS_N[1]}]
set_property SLEW FAST [get_ports {DDR3_A_DQS_P[2]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {DDR3_A_DQS_P[2]}]
set_property SLEW FAST [get_ports {DDR3_A_DQS_N[2]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {DDR3_A_DQS_N[2]}]
set_property PACKAGE_PIN K2 [get_ports {DDR3_A_DQS_P[2]}]
set_property PACKAGE_PIN J2 [get_ports {DDR3_A_DQS_N[2]}]
set_property SLEW FAST [get_ports {DDR3_A_DQS_P[3]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {DDR3_A_DQS_P[3]}]
set_property SLEW FAST [get_ports {DDR3_A_DQS_N[3]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {DDR3_A_DQS_N[3]}]
set_property PACKAGE_PIN E1 [get_ports {DDR3_A_DQS_P[3]}]
set_property PACKAGE_PIN D1 [get_ports {DDR3_A_DQS_N[3]}]
set_property SLEW FAST [get_ports {DDR3_A_DM[0]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_DM[0]}]
set_property PACKAGE_PIN N4 [get_ports {DDR3_A_DM[0]}]
set_property SLEW FAST [get_ports {DDR3_A_DM[1]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_DM[1]}]
set_property PACKAGE_PIN J4 [get_ports {DDR3_A_DM[1]}]
set_property SLEW FAST [get_ports {DDR3_A_DM[2]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_DM[2]}]
set_property PACKAGE_PIN H5 [get_ports {DDR3_A_DM[2]}]
set_property SLEW FAST [get_ports {DDR3_A_DM[3]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_DM[3]}]
set_property PACKAGE_PIN B2 [get_ports {DDR3_A_DM[3]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[0]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[0]}]
set_property PACKAGE_PIN R3 [get_ports {DDR3_A_ADD[0]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[1]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[1]}]
set_property PACKAGE_PIN U1 [get_ports {DDR3_A_ADD[1]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[2]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[2]}]
set_property PACKAGE_PIN AB1 [get_ports {DDR3_A_ADD[2]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[3]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[3]}]
set_property PACKAGE_PIN R2 [get_ports {DDR3_A_ADD[3]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[4]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[4]}]
set_property PACKAGE_PIN Y2 [get_ports {DDR3_A_ADD[4]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[5]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[5]}]
set_property PACKAGE_PIN U2 [get_ports {DDR3_A_ADD[5]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[6]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[6]}]
set_property PACKAGE_PIN AA1 [get_ports {DDR3_A_ADD[6]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[7]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[7]}]
set_property PACKAGE_PIN U3 [get_ports {DDR3_A_ADD[7]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[8]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[8]}]
set_property PACKAGE_PIN AB5 [get_ports {DDR3_A_ADD[8]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[9]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[9]}]
set_property PACKAGE_PIN T1 [get_ports {DDR3_A_ADD[9]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[10]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[10]}]
set_property PACKAGE_PIN W1 [get_ports {DDR3_A_ADD[10]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[11]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[11]}]
set_property PACKAGE_PIN W2 [get_ports {DDR3_A_ADD[11]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[12]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[12]}]
set_property PACKAGE_PIN V2 [get_ports {DDR3_A_ADD[12]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[13]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[13]}]
set_property PACKAGE_PIN Y1 [get_ports {DDR3_A_ADD[13]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[14]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[14]}]
set_property PACKAGE_PIN AB3 [get_ports {DDR3_A_ADD[14]}]
set_property SLEW FAST [get_ports {DDR3_A_ADD[15]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_ADD[15]}]
set_property PACKAGE_PIN AB2 [get_ports {DDR3_A_ADD[15]}]
set_property SLEW FAST [get_ports {DDR3_A_BA[0]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_BA[0]}]
set_property PACKAGE_PIN Y3 [get_ports {DDR3_A_BA[0]}]
set_property SLEW FAST [get_ports {DDR3_A_BA[1]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_BA[1]}]
set_property PACKAGE_PIN AA3 [get_ports {DDR3_A_BA[1]}]
set_property SLEW FAST [get_ports {DDR3_A_BA[2]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR3_A_BA[2]}]
set_property PACKAGE_PIN AA5 [get_ports {DDR3_A_BA[2]}]
set_property SLEW FAST [get_ports DDR3_A_CKE]
set_property IOSTANDARD SSTL15 [get_ports DDR3_A_CKE]
set_property PACKAGE_PIN T5 [get_ports DDR3_A_CKE]
set_property SLEW FAST [get_ports DDR3_A_WE_B]
set_property IOSTANDARD SSTL15 [get_ports DDR3_A_WE_B]
set_property PACKAGE_PIN W6 [get_ports DDR3_A_WE_B]
set_property SLEW FAST [get_ports DDR3_A_RAS_B]
set_property IOSTANDARD SSTL15 [get_ports DDR3_A_RAS_B]
set_property PACKAGE_PIN W5 [get_ports DDR3_A_RAS_B]
set_property SLEW FAST [get_ports DDR3_A_CAS_B]
set_property IOSTANDARD SSTL15 [get_ports DDR3_A_CAS_B]
set_property PACKAGE_PIN U6 [get_ports DDR3_A_CAS_B]
set_property SLEW FAST [get_ports DDR3_A_S0_B]
set_property IOSTANDARD SSTL15 [get_ports DDR3_A_S0_B]
set_property PACKAGE_PIN V5 [get_ports DDR3_A_S0_B]
set_property SLEW FAST [get_ports DDR3_A_ODT]
set_property IOSTANDARD SSTL15 [get_ports DDR3_A_ODT]
set_property PACKAGE_PIN T6 [get_ports DDR3_A_ODT]
set_property SLEW FAST [get_ports DDR3_A_RESET_B]
set_property IOSTANDARD SSTL15 [get_ports DDR3_A_RESET_B]
set_property PACKAGE_PIN V7 [get_ports DDR3_A_RESET_B]
set_property SLEW FAST [get_ports DDR3_A_CLK0_P]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR3_A_CLK0_P]
set_property SLEW FAST [get_ports DDR3_A_CLK0_N]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR3_A_CLK0_N]
set_property PACKAGE_PIN V4 [get_ports DDR3_A_CLK0_P]
set_property PACKAGE_PIN W4 [get_ports DDR3_A_CLK0_N]

set_property IOSTANDARD LVCMOS33 [get_ports FAN_FG]
set_property PACKAGE_PIN E16 [get_ports FAN_FG]

set_property IOSTANDARD LVCMOS33 [get_ports AD5592_1_SPI_CS_B]
set_property PACKAGE_PIN A20 [get_ports AD5592_1_SPI_CS_B]
set_property IOSTANDARD LVCMOS33 [get_ports AD5592_1_SPI_CLK]
set_property PACKAGE_PIN A18 [get_ports AD5592_1_SPI_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports AD5592_1_SPI_MOSI]
set_property PACKAGE_PIN A19 [get_ports AD5592_1_SPI_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports AD5592_1_SPI_MISO]
set_property PACKAGE_PIN F19 [get_ports AD5592_1_SPI_MISO]

set_property IOSTANDARD LVCMOS33 [get_ports FPGA_PLL_CLK_IN]
set_property PACKAGE_PIN E19 [get_ports FPGA_PLL_CLK_IN]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_PLL_PR0]
set_property PACKAGE_PIN C13 [get_ports FPGA_PLL_PR0]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_PLL_PR1]
set_property PACKAGE_PIN B13 [get_ports FPGA_PLL_PR1]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_PLL_OD0]
set_property PACKAGE_PIN A15 [get_ports FPGA_PLL_OD0]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_PLL_OD1]
set_property PACKAGE_PIN A16 [get_ports FPGA_PLL_OD1]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_PLL_OD2]
set_property PACKAGE_PIN A13 [get_ports FPGA_PLL_OD2]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_PLL_CE]
set_property PACKAGE_PIN F16 [get_ports FPGA_PLL_CE]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_PLL_RST_N]
set_property PACKAGE_PIN E17 [get_ports FPGA_PLL_RST_N]

set_property IOSTANDARD LVCMOS33 [get_ports FPGA_DAC_SPI_CS_N]
set_property PACKAGE_PIN G21 [get_ports FPGA_DAC_SPI_CS_N]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_DAC_SPI_SCLK]
set_property PACKAGE_PIN G22 [get_ports FPGA_DAC_SPI_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_DAC_SPI_DIN]
set_property PACKAGE_PIN F21 [get_ports FPGA_DAC_SPI_DIN]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_DAC_CLR_N]
set_property PACKAGE_PIN E21 [get_ports FPGA_DAC_CLR_N]


set_property IOSTANDARD LVCMOS18 [get_ports FPGA_TO_SFPGA_RESERVE0]
set_property PACKAGE_PIN W12 [get_ports FPGA_TO_SFPGA_RESERVE0]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_TO_SFPGA_RESERVE1]
set_property PACKAGE_PIN V13 [get_ports FPGA_TO_SFPGA_RESERVE1]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_TO_SFPGA_RESERVE2]
set_property PACKAGE_PIN V14 [get_ports FPGA_TO_SFPGA_RESERVE2]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_TO_SFPGA_RESERVE3]
set_property PACKAGE_PIN U15 [get_ports FPGA_TO_SFPGA_RESERVE3]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_TO_SFPGA_RESERVE4]
set_property PACKAGE_PIN V15 [get_ports FPGA_TO_SFPGA_RESERVE4]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_TO_SFPGA_RESERVE5]
set_property PACKAGE_PIN T14 [get_ports FPGA_TO_SFPGA_RESERVE5]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_TO_SFPGA_RESERVE6]
set_property PACKAGE_PIN T15 [get_ports FPGA_TO_SFPGA_RESERVE6]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_TO_SFPGA_RESERVE7]
set_property PACKAGE_PIN W15 [get_ports FPGA_TO_SFPGA_RESERVE7]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_TO_SFPGA_RESERVE8]
set_property PACKAGE_PIN W16 [get_ports FPGA_TO_SFPGA_RESERVE8]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_TO_SFPGA_RESERVE9]
set_property PACKAGE_PIN T16 [get_ports FPGA_TO_SFPGA_RESERVE9]

set_property IOSTANDARD LVCMOS18 [get_ports TP112]
set_property PACKAGE_PIN V22 [get_ports TP112]
set_property IOSTANDARD LVCMOS18 [get_ports TP113]
set_property PACKAGE_PIN Y21 [get_ports TP113]
set_property IOSTANDARD LVCMOS18 [get_ports TP114]
set_property PACKAGE_PIN V20 [get_ports TP114]
set_property IOSTANDARD LVCMOS18 [get_ports TP115]
set_property PACKAGE_PIN AB20 [get_ports TP115]

set_property IOSTANDARD LVCMOS33 [get_ports TP117]
set_property PACKAGE_PIN B17 [get_ports TP117]
set_property IOSTANDARD LVCMOS33 [get_ports TP118]
set_property PACKAGE_PIN B18 [get_ports TP118]
set_property IOSTANDARD LVCMOS33 [get_ports TP119]
set_property PACKAGE_PIN D17 [get_ports TP119]
set_property IOSTANDARD LVCMOS33 [get_ports TP121]
set_property PACKAGE_PIN C17 [get_ports TP121]


